### PR TITLE
C1fApp Initial version

### PR DESCRIPTION
**Pull request by etz69**
C1fApp is a threat feed aggregator. This can be used to query any of the OSINT feeds

### CODE REVIEW

**Comment by saadkadhi** [comment]
Thanks @etz69 for your contribution. We do appreciate it! We will be reviewing it as soon as feasible. 

While we have not written a policy for accepting submissions yet, please note that an issue must be created prior to making PRs. That way, we can ensure that multiple people won't waste their time working on the same analyzer. I've done it this time around 😉 

Moreover, we do not accept aliases as an author name. Can you please provide your real name, eventually with an org name (not required)? We would like to give proper credits to the original author(s).

**Comment by etz69** [comment]
Hi Saad , apologies for the omission of opening an issue and email. I have now updated my github profile ! Let me know if you want me to do the above updates and create a new pull request

**Comment by saadkadhi** [comment]
Yes please, update the author and resubmit. Thanks.

**Comment by etz69** [comment]
C1fApp is a threat feed aggregator. This can be used to query any of the OSINT feeds

**Comment by dlambrou** [comment]
addresses issue #103

**Comment by saadkadhi** [comment]
Awesome, thanks! @etz69 can you rebase your PR against develop please?

**Pull request closed without merging**
