### PR TITLE
Adding CERT-Bund analyzers (WIP, untested)

### PR DESCRIPTION
**Pull request by 3c7**
The promised PR. :tada: 

Analyzers are tested with cortexutils, but not as a whole with this repo. Hope I didn't broke something.

### CODE REVIEW

**Comment by saadkadhi** [comment]
@jeromeleonard can you please review @3c7 PR as soon as possible and accept it if everything is OK? I've added @nadouani as a reviewer as well for the template part/display in Cortex's UI.

Thanks!

**Comment by 3c7** [comment]
VMRay analyzer waits now for analysis completion.

**Comment by 3c7** [comment]
Fixed ignoring older lists.

**Comment by 3c7** [comment]
@jeromeleonard Updated the pdns analyzer

**Pull request closed without merging**
